#ifndef MOUSEBUTTONCODES_H
#define MOUSEBUTTONCODES_H

#define WAVE_MOUSE_BUTTON_1         0
#define WAVE_MOUSE_BUTTON_2         1
#define WAVE_MOUSE_BUTTON_3         2
#define WAVE_MOUSE_BUTTON_4         3
#define WAVE_MOUSE_BUTTON_5         4
#define WAVE_MOUSE_BUTTON_6         5
#define WAVE_MOUSE_BUTTON_7         6
#define WAVE_MOUSE_BUTTON_8         7
#define WAVE_MOUSE_BUTTON_LAST      WAVE_MOUSE_BUTTON_8
#define WAVE_MOUSE_BUTTON_LEFT      WAVE_MOUSE_BUTTON_1
#define WAVE_MOUSE_BUTTON_RIGHT     WAVE_MOUSE_BUTTON_2
#define WAVE_MOUSE_BUTTON_MIDDLE    WAVE_MOUSE_BUTTON_3

#endif